# Generated by Django 4.2.10 on 2025-07-13 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "create_client_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penalty",
            name="Installment",
        )
    ]
