# Generated by Django 3.0.5 on 2021-01-24 13:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='pics/avatar.png', upload_to='pics')),
                ('Father_Name', models.CharField(default='', max_length=100)),
                ('Husband_Name', models.CharField(default='', max_length=100)),
                ('Mother_Name', models.CharField(default='', max_length=100)),
                ('Wife_Name', models.CharField(default='', max_length=100)),
                ('Local_Address', models.CharField(default='', max_length=200)),
                ('Permanent_Address', models.CharField(default='', max_length=200)),
                ('Occupation', models.CharField(default='', max_length=100)),
                ('Designation', models.CharField(default='', max_length=100)),
                ('Office_Address', models.CharField(default='', max_length=200)),
                ('Phone_no1', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('Phone_no2', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('Reference_Name', models.CharField(default='', max_length=100)),
                ('Reference_No', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('Verified_By', models.CharField(max_length=100)),
                ('Date_Added', models.DateField(default=django.utils.timezone.now)),
                ('Photo_Id', models.CharField(choices=[('aadhar', 'aadhar card'), ('pan', 'pan card'), ('voter', 'Voter ID card'), ('passport', 'Passport')], default='aadhar', max_length=100)),
                ('Photo_Id_No', models.CharField(max_length=100, unique=True)),
                ('Major_Medical_Issues', models.CharField(default=None, max_length=100)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guarantor_Name', models.CharField(default='not specified', max_length=100)),
                ('Image', models.ImageField(default='pics/avatar.png', upload_to='Guarantor')),
                ('Guarantor_Father_Name', models.CharField(default='not specified', max_length=100)),
                ('Guarantor_Mother_Name', models.CharField(default='not specified', max_length=100)),
                ('Guarantor_Local_Address', models.CharField(default='not specified', max_length=200)),
                ('Guarantor_Permanent_Address', models.CharField(default='not specified', max_length=200)),
                ('Guarantor_Occupation', models.CharField(default='not specified', max_length=100)),
                ('Guarantor_Designation', models.CharField(default='not specified', max_length=100)),
                ('Guarantor_Office_Address', models.CharField(default='not specified', max_length=200)),
                ('Guarantor_Phone_no', phone_field.models.PhoneField(max_length=31)),
                ('Guarantor_Phone_no2', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('Guarantor_Security_Docs', models.TextField(default='not specified')),
            ],
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Due', models.DateField(default=django.utils.timezone.now)),
                ('Date_Paid', models.DateField(blank=True, default=None, null=True)),
                ('Installment_Due', models.FloatField(default=0)),
                ('Installment_Paid', models.FloatField(default=0)),
                ('Installment_To_Be_Paid', models.FloatField(default=0)),
                ('Pending_Amount', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['Loan_id', 'Date_Due', '-Installment_Due'],
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Principle_Amount', models.FloatField()),
                ('Frequency', models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=1)),
                ('AccNo', models.IntegerField(default=0)),
                ('Purpose', models.CharField(choices=[('c', 'Cash Loan'), ('p', 'Property Loan'), ('v', 'Vehicle Loan'), ('g', 'Gold Loan')], default='c', max_length=100)),
                ('No_Of_Installments', models.IntegerField(default=0)),
                ('Intrest_Rate', models.FloatField(default=20)),
                ('File_Charge_Percent', models.FloatField(default=5)),
                ('First_Due_Date', models.DateField(default=django.utils.timezone.now)),
                ('Loan_Date', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.BooleanField(default=False)),
                ('Remark', models.CharField(blank=True, default='None', max_length=100)),
                ('Reminder', models.DateField(default=datetime.datetime(2021, 1, 24, 13, 28, 32, 88674))),
                ('Account', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='microfinance.Accounts')),
                ('Guarantor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='microfinance.Guarantors')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Officer_Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Started', models.DateField(default=None)),
                ('Date_Ended', models.DateField(default=None, null=True)),
                ('Amount', models.FloatField(default=0)),
                ('Percent', models.FloatField(default=2)),
                ('Penalty_Calc', models.FloatField(default=0)),
                ('Penalty_Paid', models.FloatField(default=0)),
                ('Penalty_Paid_Date', models.DateField(default=None, null=True)),
                ('Status', models.BooleanField(default=False)),
                ('Installment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='microfinance.Installments')),
                ('Loan', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='microfinance.Loans')),
            ],
            options={
                'ordering': ['Loan_id', 'Date_Started'],
            },
        ),
        migrations.AddField(
            model_name='loans',
            name='Loan_Collector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='microfinance.Staff'),
        ),
        migrations.AddField(
            model_name='installments',
            name='Loan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='microfinance.Loans'),
        ),
        migrations.CreateModel(
            name='Guarantor_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='Guarantor_Documents')),
                ('Guarantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microfinance.Guarantors')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Remark', models.TextField(blank=True)),
                ('From', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='by', to='microfinance.Staff')),
                ('To', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='to', to='microfinance.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='documents')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microfinance.Clients')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microfinance.Clients'),
        ),
    ]
