# Generated by Django 4.2.10 on 2025-07-19 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0001_alter_clients_options_remove_loans_remark_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={
                "permissions": [("client_view", "Can view sensitive client data")]
            },
        ),
        migrations.RemoveField(
            model_name="loans",
            name="Remark",
        ),
        migrations.RemoveField(
            model_name="loans",
            name="Reminder",
        ),
        migrations.AlterField(
            model_name="loans",
            name="Purpose",
            field=models.CharField(
                choices=[
                    ("c", "Cash Loan"),
                    ("p", "Property Loan"),
                    ("v", "Vehicle Loan"),
                    ("g", "Gold Loan"),
                    ("e", "Electronics"),
                ],
                default="c",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="loans",
            name="remark",
            field=models.CharField(
                blank=True, default="None", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="loans",
            name="reminder",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
