# Generated by Django 4.2.10 on 2025-09-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0002_alter_clients_options_remove_loans_remark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="Installment_Due_Date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
