# Generated by Django 3.0.5 on 2021-01-24 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0003_auto_20210124_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='Reminder',
            field=models.DateField(default=datetime.datetime(2021, 1, 24, 13, 37, 10, 140889)),
        ),
    ]
