# Generated by Django 4.2.10 on 2025-10-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0003_remove_loans_security_docs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loans",
            name="Security_Docs",
        ),
        migrations.AddField(
            model_name="loans",
            name="security_docs",
            field=models.TextField(default="not specified"),
        ),
    ]
