# Generated by Django 3.0.5 on 2021-01-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0005_auto_20210124_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='Remark',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='Reminder',
        ),
    ]
