# Generated by Django 6.0 on 2026-01-03 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0005_alter_accounts_id_alter_clients_id_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="penalty",
        #     name="Installment",
        #     field=models.ForeignKey(
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="microfinance.installments",
        #     ),
        # ),
        migrations.AddField(
            model_name="penalty",
            name="Waived_Amount",
            field=models.FloatField(default=0),
        ),
    ]
