# Generated by Django 3.0.5 on 2021-01-24 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0006_auto_20210124_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='Remark',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='loans',
            name='Reminder',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 24, 16, 0, 53, 674466), null=True),
        ),
    ]
