# Generated by Django 6.0 on 2026-01-03 21:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0006_penalty_installment_penalty_waived_amount"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="penalty",
        #     name="Installment",
        #     field=models.ForeignKey(
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="microfinance.installments",
        #     ),
        # ),
        migrations.CreateModel(
            name="Waiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Waiver_Type",
                    models.IntegerField(
                        choices=[(1, "Penalty"), (2, "Interest/Loyalty")], default=1
                    ),
                ),
                ("Amount", models.FloatField(default=0)),
                ("Date_Applied", models.DateField(default=django.utils.timezone.now)),
                ("Reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="microfinance.loans",
                    ),
                ),
            ],
        ),
    ]
