# Generated by Django 6.0 on 2026-01-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0008_fix_penalty_installment_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenditures",
            name="Category",
            field=models.CharField(
                choices=[
                    ("Salary", "Salary"),
                    ("Petrol", "Petrol"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expenditures",
            name="From",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="by",
                to="microfinance.staff",
            ),
        ),
        migrations.AlterField(
            model_name="expenditures",
            name="To",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to",
                to="microfinance.staff",
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="Installment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="microfinance.installments",
            ),
        ),
    ]
