# Generated by Django 6.0 on 2026-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0009_expenditures_category_alter_expenditures_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="expenditures",
            name="Category",
            field=models.CharField(default="Other", max_length=50),
        ),
    ]
