# Generated by Django 6.0 on 2026-09-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0010_expensecategory_alter_expenditures_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="loans",
            name="Penalty_Rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loans",
            name="Principal_Threshold_Percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="Interest_Portion",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="payments",
            name="Principal_Portion",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="loans",
            name="Frequency",
            field=models.IntegerField(
                choices=[(1, "Daily"), (2, "Weekly"), (3, "Monthly"), (4, "OverDraft")],
                default=1,
            ),
        ),
    ]
