# Generated by Django 6.0 on 2026-09-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microfinance", "0011_overdraft_loan_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loans",
            name="Principal_Threshold_Percent",
        ),
        migrations.AddField(
            model_name="payments",
            name="Apply_To_Principal",
            field=models.BooleanField(default=False),
        ),
    ]
