# Generated by Django 3.0.5 on 2021-01-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0011_auto_20210124_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='Reminder',
        ),
        migrations.AddField(
            model_name='loans',
            name='Remark',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
