# Generated by Django 3.0.5 on 2021-01-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0012_auto_20210124_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='Remark',
            new_name='remark',
        ),
    ]
