# Generated by Django 3.0.5 on 2021-01-24 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0013_auto_20210124_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='Reminder',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 24, 16, 40, 42, 49592), null=True),
        ),
    ]
