# Generated by Django 3.0.5 on 2021-01-24 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0014_loans_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='Reminder',
        ),
        migrations.AddField(
            model_name='loans',
            name='reminder',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 24, 17, 46, 59, 206491), null=True),
        ),
    ]
