# Generated by Django 3.0.5 on 2021-01-26 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='Security_Docs',
            field=models.TextField(default='not specified'),
        ),
    ]
