# Generated by Django 5.1 on 2024-09-16 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0016_auto_20210126_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='reminder',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 16, 20, 7, 22, 777547), null=True),
        ),
    ]
