# Generated by Django 5.1 on 2024-09-16 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0020_rename_security_docs_loans_security_docs_and_more copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='reminder',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 16, 20, 50, 7, 971009), null=True),
        ),
    ]
