# Generated by Django 5.1 on 2024-09-16 18:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0020_rename_security_docs_loans_security_docs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'permissions': [('client_view', 'Can view sensitive client data')]},
        ),

        migrations.AddField(
            model_name='clients',
            name='ClientUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
