
# Generated by Django 5.1 on 2024-08-26 10:07

from django.db import migrations

def update_payments(apps, schema_editor):
    Installments = apps.get_model('microfinance', 'Installments')
    Penalty = apps.get_model('microfinance', 'Penalty')
    Payments = apps.get_model('microfinance', 'Payments')

    for installment in Installments.objects.all():
        if(installment.Installment_Paid>0):
            payment = Payments(Amount_Paid=installment.Installment_Paid,Date_Paid=installment.Date_Paid,Loan_id=installment.Loan_id,Payment_Type=1)

    for penalty in Penalty.objects.all():
        if(penalty.Penalty_Paid>0):
            payment = Payments(Amount_Paid=penalty.Penalty_Paid,Date_Paid=penalty.Penalty_Paid_Date,Loan_id=penalty.Loan_id,Payment_Type=2)
            payment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0020_rename_security_docs_loans_security_docs_and_more copy'),
    ]

    operations = [
        migrations.RunPython(update_payments),
    ]